#!/usr/bin/env sh
# vim:set expandtab shiftwidth=4 filetype=sh:
# SPDX-License-Identifier: Apache-2.0

#
#
# ~chewygumxx/lazy.nvim.git
# ::: :/.husky/commit-msg
#
#

npx --no -- commitlint --edit "$1"
